name: Compile pdf

on:
  push:
    branches:
      - main
    paths:
      - resume.tex
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate PDF
      uses: xu-cheng/latex-action@master
      with:
        root_file: resume.tex
        args: -pdf -interaction=nonstopmode -halt-on-error -jobname=Valentyn_Yukhymenko
    
    - name: Create legacy pdf
      run: cp Valentyn_Yukhymenko.pdf "./legacy/Valentyn_Yukhymenko_$(date +%b)_$(date +%Y).pdf"
    
    - name: Commit and push compiled pdf
      run: |
          git config --global user.name 'BaLiKfromUA'
          git config --global user.email 'valentin.yukhymenko@gmail.com'
          git add Valentyn_Yukhymenko.pdf
          git add ./legacy/**
          git commit -m "Automated compilation"
          git push